---
- name: Install APT prereqs
  ansible.builtin.apt:
    name: ['unzip', 'libgtk2.0-0', 'psmisc', 'xfonts-base', 'xfonts-utils', 'libstdc++5', 'libxtst6', 'libdb1-compat', 'tzdata']
    update_cache: true
    state: present

- name: Linux common
  ansible.builtin.include_tasks: "linux_common.yml"
