---
- name: Create new user
  hosts: "{{ nodes | default('no-such-hosts') }}"
  gather_facts: false
  become: true
  vars:
    new_user_name: devops
    new_user_password: devops
    # new_user_public_key: 'public key string to add'
  tasks:
    - name: Check packages
      iim_info:
        iim_path: /opt/IBM/InstallationManager
        product_id: com.ibm.websphere.liberty.ND
      register: iim_info

    - name: List packages intalled by IIM
      ansible.builtin.debug:
        msg: "Packages installed {{ iim_info.packages }}"
      when: iim_info.base_installed
